import type { CalendarEvent } from '../types/calendar.types';

export const mockEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'Python Basics - Introduction',
    type: 'class',
    courseId: 'course-1',
    courseName: 'Python Development',
    teacherId: 'teacher-1',
    teacherName: 'Sarah Teacher',
    meetingLink: 'https://meet.google.com/python-basics',
    date: '2024-06-15',
    startTime: '10:00',
    endTime: '11:00',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'event-2',
    title: 'Python Mid-Term Test',
    type: 'test',
    courseId: 'course-1',
    courseName: 'Python Development',
    teacherId: 'teacher-1',
    teacherName: 'Sarah Teacher',
    meetingLink: 'https://meet.google.com/python-test',
    date: '2024-06-20',
    startTime: '14:00',
    endTime: '15:30',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'event-3',
    title: 'Java OOP Concepts',
    type: 'class',
    courseId: 'course-2',
    courseName: 'Java Programming',
    teacherId: 'teacher-2',
    teacherName: 'Mike Instructor',
    meetingLink: 'https://zoom.us/j/java-oop',
    date: '2024-06-16',
    startTime: '09:00',
    endTime: '10:30',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'event-4',
    title: 'React Components Workshop',
    type: 'class',
    courseId: 'course-3',
    courseName: 'Web Development',
    teacherId: 'teacher-1',
    teacherName: 'Sarah Teacher',
    meetingLink: 'https://meet.google.com/react-workshop',
    date: '2024-06-17',
    startTime: '15:00',
    endTime: '17:00',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    isActive: true,
  },
];