import type { Notification } from '../types/notification.types';

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'class_scheduled',
    title: '📅 New Class Scheduled',
    message: 'New class "Python Basics - Introduction" scheduled for 2024-06-15 at 10:00 AM',
    recipientId: 'student-1',
    recipientRole: 'student',
    isRead: false,
    eventId: 'event-1',
    createdAt: '2024-06-14T10:00:00Z',
  },
  {
    id: 'notif-2',
    type: 'class_scheduled',
    title: '📅 New Class Scheduled',
    message: 'New class "Python Basics - Introduction" scheduled for 2024-06-15 at 10:00 AM',
    recipientId: 'student-2',
    recipientRole: 'student',
    isRead: true,
    eventId: 'event-1',
    createdAt: '2024-06-14T10:00:00Z',
  },
  {
    id: 'notif-3',
    type: 'teacher_late',
    title: '⚠️ Teacher Late Alert',
    message: 'Teacher Sarah Teacher has not joined "Python Basics - Introduction" (scheduled at 10:00 AM)',
    recipientId: 'admin-1',
    recipientRole: 'admin',
    isRead: false,
    eventId: 'event-1',
    createdAt: '2024-06-15T10:06:00Z',
  },
  {
    id: 'notif-4',
    type: 'student_enrolled',
    title: '🎓 Enrollment Successful',
    message: 'You have been enrolled in Python Development',
    recipientId: 'student-1',
    recipientRole: 'student',
    isRead: true,
    createdAt: '2024-06-01T10:00:00Z',
  },
];